fix(action): container image reference used wrong syntax
The current value caused the following error when running the action in
a different repository:

    Error: 'ghcr.io/apricote/releaser-pleaser:v0.4.1' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.

Not sure why this did not come up before, as we are also using the same
format for the CI in this repository, even if we use another tag.